controller:
  ingressClass: nginx-grafana
  ingressClassResource:
    enabled: true
    name: nginx-grafana
    default: false
  watchIngressWithoutClass: false
  ingressClassByName: true
  extraArgs:
    {
      default-ssl-certificate: "default/nginx-certs"
    }
  podAnnotations:
    {
      consul.hashicorp.com/connect-inject: "true",
      consul.hashicorp.com/connect-service: "ingress-grafana",
      consul.hashicorp.com/transparent-proxy: "true",
      consul.hashicorp.com/transparent-proxy-exclude-inbound-ports: "80,443,8443",
    }
