controller:
  ingressClass: nginx-jenkins
  ingressClassResource:
    enabled: true
    name: nginx-jenkins
    default: false
  watchIngressWithoutClass: false
  ingressClassByName: true
  extraArgs:
    {
      default-ssl-certificate: "default/nginx-certs"
    }
  podAnnotations:
    {
      consul.hashicorp.com/connect-inject: "true",
      consul.hashicorp.com/connect-service: "ingress-jenkins",
      consul.hashicorp.com/transparent-proxy: "true",
      consul.hashicorp.com/transparent-proxy-exclude-inbound-ports: "80,443,8443",
    }
