apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels: { app: influxdb }
spec:
  replicas: 1
  selector:
    matchLabels: { app: influxdb }
  template:
    metadata:
      labels: { app: influxdb }
    spec:
      containers:
        - name: influxdb
          image: influxdb:2.7
          imagePullPolicy: IfNotPresent
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: "setup"
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: "Broadly"
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: "jmeter"
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN # also referenced in grafana-deployment.yaml
              valueFrom: { secretKeyRef: { name: monitoring-secrets, key: INFLUX_TOKEN } }
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              valueFrom: { secretKeyRef: { name: monitoring-secrets, key: DOCKER_INFLUXDB_INIT_USERNAME } }
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom: { secretKeyRef: { name: monitoring-secrets, key: DOCKER_INFLUXDB_INIT_PASSWORD } }
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: influxdb-data
              mountPath: /var/lib/influxdb2
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-data-pvc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: influxdb
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels: { app: influxdb }
spec:
  selector:
    app: influxdb
  ports:
    - name: http
      port: 8086
      targetPort: 8086
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data-pvc
  labels: { app: influxdb }
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
